### PR TITLE
Fix zksync tests and implant to deploy proxy logic from clave team's one.

### PR DESCRIPTION
**Pull request by wshino**
I've implanted the deploy proxy logic from clave side into this repo. It's using SystemContractsCaller. This caused some tests to fail, but there are no problme with zksync-hardhat, clave said. I've created the issue to foundry-zksync too.

https://github.com/matter-labs/foundry-zksync/issues/509

packages/contracts/test/EmailAccountRecovery.t.sol has hit the ceiling of max bytecode capacity for zksync.
Several test cases are the same as them in packages/contracts/test/EmailAccountRecoveryForRejectRecovery.t.sol, so I removed them.

### CODE REVIEW

**Comment by SoraSuegami** [comment]
Thank you for your PR!
Could you pull the latest main branch?

**Comment by wshino** [comment]
@SoraSuegami Current implementation needs SystemContractsCaller, it requires via_ir flag in foundry.toml.
It causes long compile time whether using foundry or using foundry zksync.

To avoid this problem, we need to comment out some zksync specific implementations and imports. Additionally we can add the procedures into the docs. What do you think about this option?

**Comment by SoraSuegami** [comment]
I don't think we should enable the via_ir flag for all environments.
Is it possible to enable the flag only when compiling contracts for zksync?
> Current implementation needs SystemContractsCaller, it requires via_ir flag in foundry.toml.
Why does it require the via_ir flag?

**Comment by wshino** [comment]
@SoraSuegami As long as the following import is present, both foundry and foundry-zksync require the --via-ir flag to compile.
The reason is that the stack too deep occurs in `BootloaderUtilities.sol` in @matter-labs/zksync-contracts.

```
import {SystemContractsCaller} from "@matterlabs/zksync-contracts/l2/system-contracts/libraries/SystemContractsCaller.sol";
```

So if we want to use via-ir only with zksync, I think there is a way to comment out the above import and related logic part

**Comment by SoraSuegami** [comment]
I understand.
In that case, I agree with the approach to comment out the zksync parts for non-zksync environments due to time constraints.
We will replace it with a clear solution later.

**Pull request merged**
